plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
}

group = "com.github.mcjty"
version = project.version

base {
    archivesName = "${mod_id}-fabric-${minecraft_version}"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(Integer.parseInt(java_version))

if (System.getenv('BUILD_NUMBER') != null) {
    version += "-${System.getenv('BUILD_NUMBER')}"
}

repositories {
    mavenCentral()
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}

// The vestigial legacy API stub lives in src/api/java
sourceSets.main.java {
    srcDir 'src/api/java'
}

loom {
    def aw = file("src/main/resources/META-INF/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }
    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    modImplementation "fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${forge_config_api_port_version}"
}

processResources {
    def expandProps = [
            'version'              : version,
            'mod_id'               : mod_id,
            'mod_name'             : mod_name,
            'minecraft_version'    : minecraft_version,
            'fabric_loader_version': fabric_loader_version,
            'java_version'         : java_version
    ]
    filesMatching('fabric.mod.json') {
        expand expandProps
    }
    inputs.properties(expandProps)
}

task apiJar(type: Jar) {
    archiveClassifier = "api"
    from(sourceSets.main.output) {
        include "mcjty/lostcities/api/**"
    }
}

artifacts {
    archives apiJar
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java
        artifact apiJar

        artifactId = "lostcities"
        pom {
            name = 'LostCities'
            description = 'Lost Cities'
        }
    }
    repositories {
        if (System.getenv('local_maven') != null) {
            maven {
                name = 'local'
                url = 'file://' + System.getenv('local_maven')
            }
        }
    }
}
